# Generated by Django 3.2.3 on 2021-05-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0002_auto_20210521_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_ground',
            name='date',
        ),
        migrations.RemoveField(
            model_name='book_ground',
            name='time',
        ),
    ]
