# Generated by Django 3.2.3 on 2021-05-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0003_auto_20210521_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=20)),
                ('numbers', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
