# Generated by Django 3.2.3 on 2021-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0004_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPCOMING',
            fields=[
                ('upid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='Y-m-d')),
                ('time', models.TimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admission',
        ),
    ]
